name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install nightly toolchain with clippy available
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: clippy, rust-src, rustc-dev, llvm-tools-preview
        target: wasm32-unknown-unknown
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
